name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Generate coverage
      uses: actions-rs/tarpaulin@v0.1

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
